spring:
  application:
    name: service-B

server:
#  port: 8080
  context-path: /service-b


eureka:
  client:
    serviceUrl:
#          defaultZone: http://10.44.145.103:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    home-page-url-path: ${server.contextPath}/
    statusPageUrlPath: ${server.contextPath}/info
    healthCheckUrlPath: ${server.contextPath}/health