#热部署生效
spring:
  devtools:
    restart:
      enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**

    remote:
      secret: hg
server:
  port: 8180
  tomcat:
    max-connections: 1

