#热部署生效
spring:
  devtools:
    restart:
      enabled: true
#      pollInterval: 4000

#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
#      exclude: WEB-INF/**

    remote:
      debug:
        enabled: true
        # 这个端口跟服务器没关系
        local-port: 8000
      secret: hg
#      context-path: /demo

server:
  tomcat:
    max-connections: 1
  port: 8180
management:
  security:
    enabled: false
