FROM ubuntu:16.04
MAINTAINER hg
RUN apt-get update && apt-get install -y software-properties-common && apt-get install -y gcc && apt-get install -y gdb && apt-get install -y vim
RUN apt-get install clang -y
RUN apt-get install cmake libgtest-dev -y