server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config

#        git:
#          uri: file:cloud-config-repo/
#          uri: https://git.oschina.net/zhou666/sss.git
#          searchPaths: cloud-config-repo