server:
  port: 8080

management:
  context-path: /mgmt
  
security:
  user:
    name: user
    password: password

spring:
  boot:
    admin:
      url: http://localhost:8080
  application:
    name: admin-server

zuul:
  sensitiveHeaders: Authorization

logging:
  level:
    org.springframework.security: INFO
