/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniAdder */

#ifndef _Included_JniAdder
#define _Included_JniAdder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniAdder
 * Method:    nativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JniAdder_nativeAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
