
# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  application:
    name: eureka-cluster
  profiles:
    active: default

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:8762/eureka/

#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8763   # HTTP (Tomcat) port

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin

