
#FROM tomcat:8.0

#ENV TZ=Asia/Shanghai
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezonez


FROM tomcat:8.5-alpine
ENV TIMEZONE Asia/Shanghai

#Install tzdata for timezone management
RUN apk update \
  && apk upgrade \
  && apk --update add tzdata \
  && cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
  && echo "${TIMEZONE}" > /etc/timezone \
# Cleaning up
  && apk del tzdata \
  && rm -rf /var/cache/apk/*