FROM openjdk:8

MAINTAINER huiwq1990

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


WORKDIR /opt/spring-cloud/lib

COPY docker-timezone.jar docker-timezone.jar

ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "docker-timezone.jar"]


