FROM centos:7

MAINTAINER nimmis <kjell.havneskold@gmail.com>

RUN yum update -y && \
yum install -y wget && \
yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel && \
yum clean all

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# 设置环境变量，这是一个软连接
ENV JAVA_HOME /etc/alternatives/java_sdk

# Define default command.
CMD ["bash"]
