version: '2'
services:
    mqbroker:
        container_name: mqbroker
        image: mqbroker
        ports:
            - "10911:10911"
            - "10909:10909"
        expose:
            - 10911
            - 10909
        links:
            - mqnamesrv
        depends_on:
            - mqnamesrv
        networks:
            - rocketmq-network
    mqnamesrv:
        container_name: mqnamesrv
        image: mqnamesrv
        expose:
            - 9876
        ports:
            - "9876:9876"
        networks:
            - rocketmq-network
    mqconsole:
        container_name: mqconsole
        image: mqconsole
        expose:
            - 8888
        ports:
            - "8888:8888"
        networks:
            - rocketmq-network
networks:
    rocketmq-network:
        driver: bridge
