version: '2'
services:
    mqbroker:
        container_name: mqbroker
        image: mqbroker
        ports:
            - "10911:10911"
            - "10909:10909"
        expose:
            - 10911
            - 10909
        links:
            - mqnamesrv
        depends_on:
            - mqnamesrv
        networks:
            - mqnetwork
    mqnamesrv:
        container_name: mqnamesrv
        image: mqnamesrv
        expose:
            - 9876
        ports:
            - "9876:9876"
        networks:
            - mqnetwork
    # mqconsole:
    #     container_name: mqconsole
    #     image: mqconsole
    #     expose:
    #         - 8888
    #     ports:
    #         - "8888:8080"
    #     networks:
    #         - rocketmq-network
    mqconsole:
        container_name: mqconsole
        image: styletang/rocketmq-console-ng
        environment:
            - JAVA_OPTS=-Drocketmq.config.namesrvAddr=mqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -Xdebug -Xrunjdwp:transport=dt_socket,address=9081,server=y,suspend=n
        expose:
            - 9080
            - 9081
        ports:
            - "9080:8080"
            - "9081:9081"
        links:
            - mqnamesrv

        networks:
            - mqnetwork    
networks:
    mqnetwork:
        driver: bridge
