
spring:
  application:
    name: consumer
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0
      hystrix:
        strategy:
          enabled: true
      rxjava:
        schedulers:
          hook:
            enabled: false

server:
  port: 8180

remote:
  server: http://localhost:8181
