spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver

# 服务器配置
server:
  port: 9999

# mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations:
    - mappers/ProductMapper.xml

logging:
  level:
    com.wooyoo.learning: DEBUG

---
spring:
  profiles: test
  # 数据库配置
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql