Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "host1"
  config.vm.network "private_network", ip: "172.168.33.10"

  config.vm.provider "virtualbox" do |v|
    v.memory = "1024"
    # Change the network adapter type and promiscuous mode
    v.customize ['modifyvm', :id, '--nictype1', 'Am79C973']
    v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
    v.customize ['modifyvm', :id, '--nictype2', 'Am79C973']
    v.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
  end

  # Install bridge-utils
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get -y install bridge-utils
  # SHELL
end