version: '2'
services:

  mysql1:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - "TZ=Asia/Shanghai" # offset +09:00 / DST +09:00
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      - "3307:3306"