server:
  port: 9001

spring:
  application:
    name: notification-service
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
