FROM openjdk:8

MAINTAINER huiwq1990

COPY config-server.jar /opt/spring-cloud/lib/config-server.jar

COPY demo-config.properties /var/lib/spring-cloud/config-repo/

ENV SPRING_APPLICATION_JSON='{"spring": {"cloud": {"config": {"server": \
    {"git": {"uri": "/var/lib/spring-cloud/config-repo", "clone-on-start": true}}}}}}'

ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/spring-cloud/lib/config-server.jar"]

#VOLUME /var/lib/spring-cloud/config-repo

EXPOSE 8088
